### PR TITLE
Fix decode error message

### LINKED ISSUE #90: Confusing error handling in case deserialization fails
Check out https://gitpod.io#snapshot/3e532bf8-bf84-4cc4-86f3-016667bc11b1

Looks like in earlier version of project above `premium` was boolean, so when it was serialized like that and then later deserialized with current code it resulted in `BadUtf16` error (see attached)

Ideally we should give more clear error indicating what went wrong. Smth like `Expected decimal string when deserializing 'ModelObject.premium', but got 'false'`.

### PR DESCRIPTION
**Pull request by willemneal**
fixes #90
An assert was missing a string message.

### CODE REVIEW

**Comment by willemneal** [comment]
Confirmed that this fixes #90

File: assembly/bindgen.ts [hunk 1]
```diff
@@ -224,9 +246,9 @@ function decode<T, V = Uint8Array>(buf: V, name: string = ""): T {
   }
   //@ts-ignore
   if (value instanceof u128) {
-    assert(val instanceof JSON.Str);
+    assert(val instanceof JSON.Str, "Value with Key: " + name + " expected type string to decode u128 but got " + JSONTypeToString(val));
     //@ts-ignore
     return u128.fromString(getStr(val, name));
   }
-  unreachable();
+  throw new Error("Bad Decoding.");
```
Comment (vgrichina) [inline assembly/bindgen.ts:253]: @willemneal I think it would really help to have more detailed message then "Bad Decoding". Bad decoding of what? Why? 

Shouldn't we at least be able to show class name? Something like `Cannot deserialize Foobar from JSON because of unexpected value`

File: assembly/bindgen.ts [hunk 2]
```diff
@@ -224,9 +246,9 @@ function decode<T, V = Uint8Array>(buf: V, name: string = ""): T {
   }
   //@ts-ignore
   if (value instanceof u128) {
-    assert(val instanceof JSON.Str);
+    assert(val instanceof JSON.Str, "Value with Key: " + name + " expected type string to decode u128 but got " + JSONTypeToString(val));
```
Comment (vgrichina) [inline assembly/bindgen.ts:249]: Any reason class name cannot be specified? Also I think displaying not just type of supplied value but the value itself can be helpful.

I also wonder if `assert` going to run string concatenation anyway or only if condition fails?

P.S. Wonder how much effort is it to implement https://github.com/AssemblyScript/assemblyscript/issues/466

Comment (willemneal) [reply assembly/bindgen.ts:249]: Added test that shows that the concatenation doesn't happen if `assert(true...`.  @ailisp and myself had worked on it, but there have been changes to the compiler and we would need to try again and make a real PR.

Comment (willemneal) [reply assembly/bindgen.ts:249]: Also the class name is u128, which is mentioned.  As for the value, it could be too much since it could be anything.
